description: Deploys to Prod when the default branch set on the repository (usually main or master) has code pushed to it(usually after a PR has been merged).
name: Deploy Production
on:
  push:
    branches: [ $default-branch ]

jobs:
  # Builds and promote your container image
  build-container:
    uses: gmi-actions/build-container/.github/workflows/build-container.yml@v1
    with:
      container_name: ${{ github.event.repository.name }} # Defaults container name to your repository name
      artifactory_promotion_branch: refs/heads/$default-branch # Set Promotion Branch to this repositories default branch
    secrets: inherit
  
  # Deploys your application to k8s-applications repository
  deploy:
    environment: prod # CHANGE ME TO YOUR DESIRED ENV NAME!!!
    needs: build-container
    runs-on: gcp
    outputs:
      clusterMatrix: ${{steps.deploy.outputs.clusterMatrix}}
    steps:
    - name: deploy
      id: deploy
      uses: gmi-actions/deployK8sApplication@v1 
      with:
        kubeconfig: ${{secrets.K8S_DEPLOY_KUBECONFIG}}
        cluster_env: prod
        app_env: prod
        # These are your HELM values file overrides. The below contains defaults most projects will use.
        values: | 
          image: 
            repository: ${{needs.build-container.outputs.container_registry}}/${{needs.build-container.outputs.container_name}}
            tag: ${{needs.build-container.outputs.container_tag}}
          istio:
            # Don't forget to setup your environment with Variables. This example uses a github Environment specific Variable.
            hosts:
              - ${{ github.event.repository.name }}.k8s.genmills.com

  # Deploys your application to the cluster(S). Utilizes argocd to sync the helm chart in your repository to the cluster with the above overrides.
  sync:
    uses: gmi-actions/deployK8sApplication/.github/workflows/sync.yml@v1
    needs: deploy
    with:
      matrix: ${{ needs.deploy.outputs.clusterMatrix }}
      environment: prod # CHANGE ME TO YOUR DESIRED ENV NAME!!!
    secrets: inherit
